// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZdfwpIy1EFGVHdTAfbvFnQtWHyAPyh6Y',
    appId: '1:981765681774:web:d37ee4f17d5a935dc62c7f',
    messagingSenderId: '981765681774',
    projectId: 'polar-1c032',
    authDomain: 'polar-1c032.firebaseapp.com',
    storageBucket: 'polar-1c032.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBohUfSgX52a8dNzUk7acrNY5XB3aaayVw',
    appId: '1:981765681774:android:bbd0255515550c3bc62c7f',
    messagingSenderId: '981765681774',
    projectId: 'polar-1c032',
    storageBucket: 'polar-1c032.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYbP35aB1RqlzVZRS9MvdZV_z1gz-tp3g',
    appId: '1:981765681774:ios:99d8e67ffc095f9bc62c7f',
    messagingSenderId: '981765681774',
    projectId: 'polar-1c032',
    storageBucket: 'polar-1c032.appspot.com',
    iosClientId: '981765681774-adis3omi0ub2aabkeq52p3vqs4pd4krt.apps.googleusercontent.com',
    iosBundleId: 'com.example.polar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYbP35aB1RqlzVZRS9MvdZV_z1gz-tp3g',
    appId: '1:981765681774:ios:99d8e67ffc095f9bc62c7f',
    messagingSenderId: '981765681774',
    projectId: 'polar-1c032',
    storageBucket: 'polar-1c032.appspot.com',
    iosClientId: '981765681774-adis3omi0ub2aabkeq52p3vqs4pd4krt.apps.googleusercontent.com',
    iosBundleId: 'com.example.polar',
  );
}
